const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#F97316",
    background: "#0B1C3D",
    foreground: "#FFFFFF",
    card: "#132144",
    cardForeground: "#FFFFFF",
    primary: "#F97316",
    primaryForeground: "#FFFFFF",
    secondary: "#162040",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2B4A",
    mutedForeground: "#8BA0C4",
    accent: "#1E3060",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3060",
    input: "#1A2B4A",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#F97316",
    background: "#0B1C3D",
    foreground: "#FFFFFF",
    card: "#132144",
    cardForeground: "#FFFFFF",
    primary: "#F97316",
    primaryForeground: "#FFFFFF",
    secondary: "#162040",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2B4A",
    mutedForeground: "#8BA0C4",
    accent: "#1E3060",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3060",
    input: "#1A2B4A",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
  },
  radius: 16,
};

export default colors;
